config/routes.rb
Rails.application.routes.draw do
  resources :permissions
  resources :roles

  devise_for :users,
             controllers: {sessions: 'users/sessions',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           registrations: 'users/registrations',
                           passwords: 'users/passwords',
                           password_expired: 'users/password_expired'},
             path: '/',
             path_names: {sign_in: 'login',
                          sign_out: 'logout'}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    authenticate :user do
      # Shows all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations

      # Create new users.
      get '/users/new', to: 'users/registrations#new_user', as: :new_user
      post '/users', to: 'users/registrations#create_user', as: :create_user

      # Edit page for a user profile.
      get '/users/edit', to: 'users/registrations#edit', as: :edit_profile
      match '/users', to: 'users/registrations#update', as: :update_profile, via: [:patch, :put]

      # User image
      match '/users/:id/get_user_image', to: 'users/registrations#get_user_image', as: :get_user_image, via: [:patch, :put]

      # Edit page for all users.
      get '/users/:id/edit', to: 'users/registrations#edit_user', as: :edit_user
      match '/users/:id', to: 'users/registrations#update_user', as: :update_user, via: [:patch, :put]

      # Show page for a user.
      get '/users/:id', to: 'users/registrations#show', as: :user

      # Edit a user password.
      get '/users/:id/change_password', to: 'users/registrations#change_password', as: :change_password
      match 'save_password/:id', to: 'users/registrations#save_password', as: :save_password,
            via: [:patch, :put]

      # Destroys a user
      delete '/users/:id', to: 'users/registrations#destroy', as: :destroy_user_registration

      # Gets a JS response with all controller actions.
      get '/permissions/new/get_controller_actions', to: 'permissions#get_controller_actions', as: :get_controller_actions

      # Posts seed data from permissions in relation with their role.
      post '/permissions/generate_seeds', to: 'permissions#generate_seeds', as: :generate_seeds

      # Displays a role with every permission granted.
      get '/roles/:role_id/permissions', to: 'roles#role_permissions', as: :role_permissions

      # Creates a relationship between roles and permissions.
      post '/roles/:role_id/assign_permissions', to: 'roles#assign_permissions', as: :assign_permissions

      # Sets the language to spanish.
      get '/set_language/spanish'

      # Sets the language to english.
      get '/set_language/english'
    end
  end
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id          :integer          not null, primary key
#  name        :string
#  key         :string
#  description :text
#  scope       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Role < ActiveRecord::Base
  has_many :users
  has_many :permission_role, dependent: :destroy
  has_many :permissions, through: :permission_role

  validates_presence_of :name, :description
  validates_uniqueness_of :key, allow_blank: true
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  add_breadcrumb proc { I18n.t('breadcrumbs.roles') }, :roles_path

  # GET /roles
  # GET /roles.json
  def index
    @search_roles = Role.ransack(params[:q])
    @roles = @search_roles.result.paginate(page: params[:page], per_page: 20)
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    add_breadcrumb @role.name, :role_path
  end

  # GET /roles/new
  def new
    add_breadcrumb t('helpers.new'), :new_role_path
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
    add_breadcrumb t('helpers.edit'), :edit_role_path
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(update_role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    if @role.key == 'god'
      redirect_to :back, alert: t('notifications_masc.alert.resource.destroyed',
                                  resource: t('roles.form.resource'))
    else
      if @role.users.empty?
        @role.destroy
        respond_to do |format|
          format.html { redirect_to roles_url }
          format.json { head :no_content }
        end
      else
        redirect_to :back
        flash[:notice] = t('notifications_masc.alert.resource.role_dependency', resource: @role.name)
      end
    end
  end

  # Return the role that has been selected with the existing permissions
  def role_permissions
    add_breadcrumb t('breadcrumbs.permissions'), :roles_path
    @role = Role.find(params[:role_id])
    @permissions = Permission.order('controller').group_by { |t| t.controller }
  end

  # Create the relation between the the role and the permissions selected and writes them into the database
  def assign_permissions
    @role = Role.find params[:role_id]
    @role.permissions.delete_all
    if params[:permissions_ids].respond_to? 'each'
      params[:permissions_ids].each do |permission|
        PermissionRole.create(role_id: @role.id, permission_id: permission[1])
      end
    end

    respond_to do |format|
      format.html { redirect_to roles_url, notice: t('notifications_masc.info.permissions_assigned') }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_params
    params.require(:role).permit(:name, :key, :description, :scope, permission_ids: [])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def update_role_params
    params.require(:role).permit(:name, :description, :scope, permission_ids: [])
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.slim
= form_for(role, role: 'form', html: {class: 'form-horizontal'}, validate: true) do |f|
  .box-body
    .row.form-group
      = f.label :name, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :name, class: 'form-control', placeholder: t('.name'), autofocus: true
    .row.form-group
      = f.label :key, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :key, class: 'form-control', placeholder: t('.key')
    .row.form-group
      = f.label :description, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_area :description, class: 'form-control', placeholder: t('.description')
  .box-footer
    = f.button "<i class='fa fa-floppy-o'></i> #{t('helpers.submit.submit', model: t('.resource'))}".html_safe,
            class: 'btn btn-primary btn-flat', type: 'submit'
    = link_to roles_path, class: 'btn btn-default btn-flat' do
      i.fa.fa-list
      =< t('.back')

app/views/roles/edit.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          h3.box-title
            = t('.title')
        = render 'form', role: @role

app/views/roles/index.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          .row
            .col-xs-6.col-md-8.col-lg-9
              h3.box-title
                = t('.title')
            .col-xs-6.col-md-4.col-lg-3
              .box-tools.pull-right
                = search_form_for @search_roles do |f|
                  .input-group.input-group-sm.search
                    = f.text_field :name_or_description_or_key_cont, class: 'form-control',
                            placeholder: t('helpers.search')
                    .input-group-btn
                      button [class="btn btn-default" type="submit"]
                        i [class="fa fa-search"]
                .tools
                  button [type="button" class="btn btn-default btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="false"]
                    i.fa.fa-cog
                  ul [class="dropdown-menu dropdown-menu-right" role="menu"]
                    li 
                      a [href="#"]
                        i.fa.fa-file-excel-o
                        = t('helpers.export_excel')
                    li = link_to "<i class='fa fa-trash'></i> #{t 'helpers.dump_destroy'}".html_safe, '#'
        .box-body
          .dataTables_wrapper
            .row
              .col-sm-12
                .table-responsive
                  table.table.table-bordered.table-hover.dataTable
                    thead
                      tr
                        th.table-checkbox
                          .checkbox.icheck
                            input [type="checkbox" class="icheck-me" data-skin="square" data-color="blue"]
                        th = t('.name')
                        th = t('.key')
                        th = t('.description')
                        th.actions_header
                          = t('helpers.actions')
                    tbody
                      - @roles.each do |role|
                        tr.show_actions
                          td.table-checkbox
                            .checkbox.icheck
                              input [type="checkbox" class="icheck-me" data-skin="square" data-color="blue"]
                          td = role.name
                          td = role.key
                          td = role.description
                          td
                            .actions
                              = link_item '<i class="fa fa-search"></i>'.html_safe, role, title: t('helpers.show'),
                                      class: 'btn btn-xs btn-success btn-flat'
                              = link_item '<i class="fa fa-edit"></i>'.html_safe, edit_role_path(role),
                                      class: 'btn btn-xs btn-primary btn-flat', title: t('helpers.edit')
                              - if has_policy(Role, %w(destroy)) && role.key != 'god'
                                = link_to '<i class="fa fa-trash-o"></i>'.html_safe, '#', title: t('helpers.destroy'),
                                        class: 'btn btn-xs btn-danger btn-flat btn-destroy',
                                        data: {'resource': :roles, 'resource-id': role.id,
                                              'resource-message': t('questions.destroy', resource: t('.resource'),
                                                                  name: role.name)}
                              = link_item '<i class="fa fa-ban"></i>'.html_safe, role_permissions_url(role.id),
                                      title: t('.permissions'), class: 'btn btn-xs btn-warning btn-flat'
            .row
              .col-sm-5
                .dataTables_info
                  = pluralize(@roles.count, t('.one'), t('.other'))
              .col-sm-7
                .dataTables_paginate.paging_simple_numbers
                  = custom_paginator(@roles)

app/views/roles/new.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          h3.box-title
            = t('.title')
        = render 'form', role: @role

app/views/roles/role_permissions.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          h3.box-title
            = @role.name
        = form_tag(assign_permissions_url, html: {class: 'form-horizontal'}) do
          .box-body
            .row.form-group
              - @permissions.each do |controller, permissions|
                .col-xs-12
                  .box.box-solid
                    .box-header.with-border
                      h3.box-title
                        = controller.to_s
                    .box-body
                      .row.form-group
                        - permissions.each do |permission|
                          .col-xs-12.col-sm-6.col-md-4.col-lg-3
                            .check-container
                              .checkbox.icheck
                                = check_box_tag "permissions_ids[#{permission.id}]", permission.id,
                                  @role.permissions.include?(permission), class: 'icheck-me', data: {skin: 'square', color: 'blue'}
                              .permissions-description
                                = permission.name
          .box-footer
            = submit_tag t('.save_permissions'), class: 'btn btn-primary btn-flat'
            = link_to roles_path, class: 'btn btn-default btn-flat' do
              i.fa.fa-list
              =< t('.back')

app/views/roles/show.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          h3.box-title
            = @role.name
        .box-body
          strong = t('.key')
          p.text-muted
            = @role.key
          strong = t('.description')
          p.text-muted
            = @role.description
        .box-footer
          = link_to edit_role_path(@role), class: 'btn btn-primary btn-flat', title: t('helpers.edit') do
            i.fa.fa-pencil-square-o
            =< t('helpers.edit')
          = link_to roles_path, class: 'btn btn-default btn-flat' do
            i.fa.fa-list
            =< t('.back')