config/routes.rb
Rails.application.routes.draw do
  resources :permissions
  resources :roles

  devise_for :users,
             controllers: {sessions: 'users/sessions',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           registrations: 'users/registrations',
                           passwords: 'users/passwords',
                           password_expired: 'users/password_expired'},
             path: '/',
             path_names: {sign_in: 'login',
                          sign_out: 'logout'}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    authenticate :user do
      # Shows all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations

      # Create new users.
      get '/users/new', to: 'users/registrations#new_user', as: :new_user
      post '/users', to: 'users/registrations#create_user', as: :create_user

      # Edit page for a user profile.
      get '/users/edit', to: 'users/registrations#edit', as: :edit_profile
      match '/users', to: 'users/registrations#update', as: :update_profile, via: [:patch, :put]

      # User image
      match '/users/:id/get_user_image', to: 'users/registrations#get_user_image', as: :get_user_image, via: [:patch, :put]

      # Edit page for all users.
      get '/users/:id/edit', to: 'users/registrations#edit_user', as: :edit_user
      match '/users/:id', to: 'users/registrations#update_user', as: :update_user, via: [:patch, :put]

      # Show page for a user.
      get '/users/:id', to: 'users/registrations#show', as: :user

      # Edit a user password.
      get '/users/:id/change_password', to: 'users/registrations#change_password', as: :change_password
      match 'save_password/:id', to: 'users/registrations#save_password', as: :save_password,
            via: [:patch, :put]

      # Destroys a user
      delete '/users/:id', to: 'users/registrations#destroy', as: :destroy_user_registration

      # Gets a JS response with all controller actions.
      get '/permissions/new/get_controller_actions', to: 'permissions#get_controller_actions', as: :get_controller_actions

      # Posts seed data from permissions in relation with their role.
      post '/permissions/generate_seeds', to: 'permissions#generate_seeds', as: :generate_seeds

      # Displays a role with every permission granted.
      get '/roles/:role_id/permissions', to: 'roles#role_permissions', as: :role_permissions

      # Creates a relationship between roles and permissions.
      post '/roles/:role_id/assign_permissions', to: 'roles#assign_permissions', as: :assign_permissions

      # Sets the language to spanish.
      get '/set_language/spanish'

      # Sets the language to english.
      get '/set_language/english'
    end
  end
end

app/views/layouts/_account_dropdown.html.slim
li.dropdown.user.user-menu
  / Menu Toggle Button
  a.dropdown-toggle data-toggle='dropdown' href='#'
    / The user image in the navbar
    = image_tag current_user.avatar.url(:small), class: 'user-image',
                onerror: "this.src='#{image_path 'user_image.png'}'"
    / hidden-xs hides the username on small devices so only the image appears.
    span.hidden-xs
      = current_user.email
  ul.dropdown-menu
    / The user image in the menu
    li.user-header
      = image_tag current_user.avatar.url(:medium), class: 'img-circle',
                  onerror: "this.src='#{image_path 'user_image.png'}'"
      p
        = current_user.email
    / Menu Footer
    li.user-footer
      .pull-left
        = link_to t('.profile'), edit_profile_path, class: 'btn btn-default btn-flat'
      .pull-right
        = link_to t('.log_out'), destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat'

app/views/layouts/_content.html.slim
.content-wrapper
  / Content Header (Page header)
  section.content-header
    h3
    ol.breadcrumb
      li
        i.fa.fa-dashboard
        = render_breadcrumbs tag: :li, separator: '<i class="fa fa-angle-right" style="padding: 0 5px;"></i>'.html_safe
  = yield

app/views/layouts/_control_sidebar.html.slim
aside.control-sidebar.control-sidebar-dark
  ul.nav.nav-tabs.nav-justified.control-sidebar-tabs
    li.active
      a [href="#control-sidebar-settings" data-toggle="tab" aria-expanded="true"]
        i.fa.fa-wrench
    li
      a [href="#control-home-settings" data-toggle="tab" aria-expanded="true"]
        i.fa.fa-home
    li
      a [href="#control-stats-settings" data-toggle="tab" aria-expanded="true"]
        i.fa.fa-bar-chart
  .tab-content
    #control-sidebar-settings.tab-pane.active
      div
        h4.control-sidebar-heading = t('layouts.control_side_bar.skins')
        ul.list-unstyled.clearfix
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-blue"]
              div
                span.skin-span [style="width: 20%; background: #367fa9;"]
                span.bg-light-blue.skin-span [style="width: 80%;"]
              div
                span.skin-span [style="width: 20%; background: #222d32; height: 20px"]
                span.skin-span [style="width: 80%; background: #f4f5f7; height: 20px"]
            p.text-center.no-margin Blue
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-black"]
              div
                span.skin-span [style="width: 20%; background: #fefefe;"]
                span.skin-span [style="width: 80%; background: #fefefe;"]
              div
                span.skin-span [style="width: 20%; background: #222; height: 20px"]
                span.skin-span [style="width: 80%; background: #f4f5f7; height: 20px"]
            p.text-center.no-margin Black
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-purple"]
              div
                span.skin-span.bg-purple-active [style="width: 20%;"]
                span.skin-span.bg-purple [style="width: 80%;"]
              div
                span.skin-span [style="width: 20%; background: #222d32; height: 20px"]
                span.skin-span [style="width: 80%; background: #f4f5f7; height: 20px"]
            p.text-center.no-margin Purple
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-green"]
              div
                span.skin-span.bg-green [style="width: 20%;"]
                span.skin-span.bg-green-active [style="width: 80%;"]
              div
                span.skin-span [style="width: 20%; height: 20px; background: #222d32;"]
                span.skin-span [style="width: 80%; height: 20px; background: #f4f5f7"]
            p.text-center.no-margin Green
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-red"]
              div
                span.skin-span.bg-red [style="width: 20%;"]
                span.skin-span.bg-red-active [style="width: 80%;"]
              div
                span.skin-span [style="width: 20%; height: 20px; background: #222d32;"]
                span.skin-span [style="width: 80%; height: 20px; background: #f4f5f7"]
            p.text-center.no-margin Red
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-yellow"]
              div
                span.skin-span.bg-yellow [style="width: 20%;"]
                span.skin-span.bg-yellow-active [style="width: 80%;"]
              div
                span.skin-span [style="width: 20%; height: 20px; background: #222d32;"]
                span.skin-span [style="width: 80%; height: 20px; background: #f4f5f7"]
            p.text-center.no-margin Yellow
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-blue-light"]
              div
                span.skin-span [style="width: 20%; background: #367fa9;"]
                span.bg-light-blue.skin-span [style="width: 80%;"]
              div
                span.skin-span [style="width: 20%; height: 20px; background: #f9fafc;"]
                span.skin-span [style="width: 80%; height: 20px; background: #f4f5f7"]
            p.text-center.no-margin Blue Light
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-black-light"]
              div
                span.skin-span [style="width: 20%; background: #fefefe;"]
                span.skin-span [style="width: 80%; background: #fefefe;"]
              div
                span.skin-span [style="width: 20%; height: 20px; background: #f9fafc;"]
                span.skin-span [style="width: 80%; height: 20px; background: #f4f5f7"]
            p.text-center.no-margin Black Light
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-purple-light"]
              div
                span.skin-span.bg-purple-active [style="width: 20%;"]
                span.skin-span.bg-purple [style="width: 80%;"]
              div
                span.skin-span [style="width: 20%; height: 20px; background: #f9fafc;"]
                span.skin-span [style="width: 80%; height: 20px; background: #f4f5f7"]
            p.text-center.no-margin Purple Light
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-green-light"]
              div
                span.skin-span.bg-green [style="width: 20%;"]
                span.skin-span.bg-green-active [style="width: 80%;"]
              div
                span.skin-span [style="width: 20%; height: 20px; background: #f9fafc;"]
                span.skin-span [style="width: 80%; height: 20px; background: #f4f5f7"]
            p.text-center.no-margin Green Light
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-red-light"]
              div
                span.skin-span.bg-red [style="width: 20%;"]
                span.skin-span.bg-red-active [style="width: 80%;"]
              div
                span.skin-span [style="width: 20%; height: 20px; background: #f9fafc;"]
                span.skin-span [style="width: 80%; height: 20px; background: #f4f5f7"]
            p.text-center.no-margin Red Light
          li.skin
            a.clearfix.full-opacity-hover.skin-anchor [href="javascript:void(0)" data-skin="skin-yellow-light"]
              div
                span.skin-span.bg-yellow [style="width: 20%;"]
                span.skin-span.bg-yellow-active [style="width: 80%;"]
              div
                span.skin-span [style="width: 20%; height: 20px; background: #f9fafc;"]
                span.skin-span [style="width: 80%; height: 20px; background: #f4f5f7"]
            p.text-center.no-margin Yellow Light
    #control-home-settings.tab-pane
      div
        h4.control-sidebar-heading = t('layouts.control_side_bar.home')
    #control-stats-settings.tab-pane
      div
        h4.control-sidebar-heading = t('layouts.control_side_bar.stats')
.control-sidebar-bg [style="position: fixed; height: auto;"]

app/views/layouts/_footer.html.slim
footer.main-footer
  strong
    | Copyright © 2016
    =< link_to 'Universidad Autónoma de Chihuahua', 'http://www.uach.mx', target: '_blank'
    =< t('.rights')

app/views/layouts/_head.html.slim
head
  meta charset='utf-8' /
  meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1' /

  = display_meta_tags site: 'Template', title: page_title, reverse: true

  meta name='description' content='' /
  meta name='viewport' content='width=device-width' /

  = render 'layouts/javascripts'

  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true
  = javascript_include_tag 'modernizr', 'data-turbolinks-track': true

  = csrf_meta_tag
  / Set language to the locale variable
  = javascript_tag "window.locale = #{I18n.locale.to_s.inspect};"
  = javascript_tag "window.I18n = #{current_translations.to_json.html_safe};"

app/views/layouts/_header.html.slim
header.main-header
  / Logo
  = link_to authenticated_root_path, class: 'logo' do
    span.logo-mini
      | Logo
    / logo for regular state and mobile devices
    span.logo-lg
      b
        | Logo
  / Header Navbar
  nav.navbar.navbar-static-top role='navigation'
    / Sidebar toggle button
    a.sidebar-toggle href='#' data-toggle='offcanvas' role='button'
      span.sr-only Toggle navigation
    / Navbar Right Menu
    .navbar-custom-menu
      ul.nav.navbar-nav
        li.language-btn [title="#{t('.select_lang')}"]
          - if I18n.locale == :es
            a.first href="javascript:;"
              i.fa.fa-flag.fa-lg
              span.hidden-xs
                =< t('.language')
            = link_to set_language_english_path do
              span.flag-icon.flag-icon-us
              span.hidden-xs
                =< t('.change_lang')
          - else
            a.first href="javascript:;"
              i.fa.fa-flag.fa-lg
              span.hidden-xs
                =< t('.language')
            = link_to set_language_spanish_path do
              span.flag-icon.flag-icon-es
              span.hidden-xs
                =< t('.change_lang')
        = render 'layouts/account_dropdown'
        li
          a [href="javascript:;" data-toggle="control-sidebar"]
            i.fa.fa-gears

app/views/layouts/_javascripts.html.slim
= javascript_include_tag 'application', 'data-turbolinks-track': true
= yield :javascripts

app/views/layouts/_side_menu.html.slim
aside.main-sidebar
  section.sidebar
    /! Sidebar Menu
    ul.sidebar-menu
      li.header MENU
      li.treeview
        a href='#'
          i.fa.fa-share
          span Link
          i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          li
            = link_to "<i class='fa fa-circle-o'></i> Link in level 2".html_safe, '#'
      li.header ADMIN
      - if has_policy(Role, %w(new index))
        li.treeview
          a href='#'
            i.fa.fa-user-secret
            span = t('.roles')
            i.fa.fa-angle-left.pull-right
          ul.treeview-menu
            li
              = link_item "<i class='fa fa-circle-o'></i> #{t '.new_role'}".html_safe, new_role_path
            li
              = link_item "<i class='fa fa-circle-o'></i> #{t '.roles'}".html_safe, roles_path
      - if has_policy(Permission, %w(new index))
        li.treeview
          a href='#'
            i.fa.fa-ban
            span = t('.permissions')
            i.fa.fa-angle-left.pull-right
          ul.treeview-menu
            li
              = link_item "<i class='fa fa-circle-o'></i> #{t '.new_permission'}".html_safe, new_permission_path
            li
              = link_item "<i class='fa fa-circle-o'></i> #{t '.permissions'}".html_safe, permissions_path
        - if has_policy(User, %w(new_user index), 'Users::Registration')
          li.treeview
            a href='#'
              i.fa.fa-user
              span = t('.users')
              i.fa.fa-angle-left.pull-right
            ul.treeview-menu
              li
                = link_item "<i class='fa fa-circle-o'></i> #{t '.new_user'}".html_safe, new_user_path
              li
                = link_item "<i class='fa fa-circle-o'></i> #{t '.users'}".html_safe, user_registrations_path

app/views/layouts/application.html.slim
doctype 5
html.no-js
  = render 'layouts/head'

  body.hold-transition.sidebar-mini.skin-blue
    - unless flash.empty?
      script [type="text/javascript"]
        | var time = 5000;
          var increment = 500;
        - flash.each do |f|
          - type = f[0].to_s.split('_')[0].gsub('alert', 'warning').gsub('notice', 'info')
          | toastr.options = {
             closeButton: true,
             debug: false,
             newestOnTop: true,
             progressBar: false,
             positionClass: 'toast-top-right',
             preventDuplicates: false,
             onclick: null,
             showDuration: 300,
             hideDuration: 3000,
             timeOut: time,
             extendedTimeOut: '1000',
             showEasing: 'swing',
             hideEasing: 'linear',
             showMethod: 'fadeIn',
             hideMethod: 'fadeOut'
            };
            toastr['#{type}']('#{f[1]}');
            time += increment;
    .wrapper
      = render 'layouts/header'
      = render 'layouts/side_menu'
      = render 'layouts/content'
      = render 'layouts/footer'
      = render 'layouts/control_sidebar'

app/views/layouts/out_system.html.slim
doctype html
html.no-js
  head
    meta charset='utf-8' /
    meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1' /

    = display_meta_tags site: 'Template', title: page_title, reverse: true

    meta name='description' content='' /
    meta name='viewport' content='width=device-width' /

    = javascript_include_tag 'out_system', 'data-turbolinks-track': true

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'modernizr', 'data-turbolinks-track': true

    = csrf_meta_tag
    / Set language to the locale variable
    = javascript_tag "window.locale = #{I18n.locale.to_s.inspect};"
    = javascript_tag "window.I18n = #{current_translations.to_json.html_safe};"

  body.hold-transition.register-page
    - unless flash.empty?
      script [type="text/javascript"]
        | var time = 5000;
              var increment = 500;
        - flash.each do |f|
          - type = f[0].to_s.split('_')[0].gsub('alert', 'warning').gsub('notice', 'info')
          | toastr.options = {
                 closeButton: true,
                 debug: false,
                 newestOnTop: true,
                 progressBar: false,
                 positionClass: 'toast-top-right',
                 preventDuplicates: false,
                 onclick: null,
                 showDuration: 300,
                 hideDuration: 3000,
                 timeOut: time,
                 extendedTimeOut: '1000',
                 showEasing: 'swing',
                 hideEasing: 'linear',
                 showMethod: 'fadeIn',
                 hideMethod: 'fadeOut'
                };
                toastr['#{type}']('#{f[1]}');
                time += increment;
    .wrapper
      = yield